# Generated by Django 4.2 on 2023-05-07 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='rater.movie'),
            preserve_default=False,
        ),
    ]
