# Generated by Django 4.2 on 2023-05-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0003_rating_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='created_at',
        ),
    ]
