# Generated by Django 4.2 on 2023-05-07 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0004_remove_rating_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='movie',
        ),
    ]
