# Generated by Django 4.2 on 2023-05-10 18:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rater', '0008_visitor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visitor',
            new_name='User',
        ),
    ]
