# Generated by Django 4.2 on 2023-05-10 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0009_rename_visitor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passwords',
        ),
    ]
